name: Publish

on: push

jobs:
  freeze:
    name: "Freeze: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install tox
      run: pip install tox

    - name: Build binary
      run: tox -e freeze

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: shub-${{ matrix.os }}
        path: dist_bin/shub
